import { existsSync, mkdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { generateIndex, writeEntry } from './okf.js';

export const KNOWLEDGE_SUBDIRS = ['wiki', 'guidelines', 'review-notes'] as const;

/**
 * Repository-local knowledge bundle in OKF layout:
 *
 *   <repo>/<knowledge.path>/
 *     index.md          generated table of contents (the only file injected
 *                       into prompts; details are read on demand by the agent)
 *     wiki/             repository understanding, generated by `knowledge wiki`
 *     guidelines/       human-authored review guidelines / internal rules
 *     review-notes/     learnings from past reviews (phase 2 automation)
 */
export class KnowledgeStore {
  readonly root: string;

  constructor(repoPath: string, relPath: string) {
    this.root = join(repoPath, relPath);
  }

  exists(): boolean {
    return existsSync(join(this.root, 'index.md'));
  }

  init(): void {
    mkdirSync(this.root, { recursive: true });
    for (const dir of KNOWLEDGE_SUBDIRS) {
      mkdirSync(join(this.root, dir), { recursive: true });
    }
    const starter = join(this.root, 'guidelines', 'review-policy.md');
    if (!existsSync(starter)) {
      writeEntry(this.root, {
        path: 'guidelines/review-policy.md',
        frontmatter: {
          type: 'guideline',
          title: 'レビュー方針',
          tags: ['policy'],
        },
        body: [
          'このリポジトリのレビューで重視する観点を記述してください。エージェントはレビュー時にこのディレクトリを参照します。',
          '',
          '例:',
          '- エラーハンドリング: 例外を握りつぶさない',
          '- 命名: ドメイン用語集に従う',
          '- 禁止事項: 直接SQLを書かずリポジトリ層を経由する',
        ].join('\n'),
      });
    }
    this.refreshIndex();
  }

  refreshIndex(): void {
    generateIndex(this.root);
  }

  readIndex(): string | undefined {
    const file = join(this.root, 'index.md');
    return existsSync(file) ? readFileSync(file, 'utf8') : undefined;
  }
}
